### ISSUE TITLE
Add table sorting

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/releases.demo.haus#12]
The table should default to sort by age of the last staging build with the ability to change the sorting on the other table headers.

**Comment by nottrobin** [comment]
Do we really need the ability to change the sorting? If we make it so the domains where master, staging and production are in sync are sent to the bottom, and only the ones with new changes are surfaced, in order of recency, don't you think that the relevant site should always be pretty obvious near the top?

Also I'm thinking this might evolve way beyond your traditional table, where each row contains only headline info and is expandable, so it might not be clear what the "table headers" are.
